export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: number;
          email: string;
          full_name: string;
          role: string;
          directorate_id: number | null;
          department_id: number | null;
          border_point_id: number | null;
          is_active: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          email: string;
          full_name: string;
          role: string;
          directorate_id?: number | null;
          department_id?: number | null;
          border_point_id?: number | null;
          is_active?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          email?: string;
          full_name?: string;
          role?: string;
          directorate_id?: number | null;
          department_id?: number | null;
          border_point_id?: number | null;
          is_active?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      consignments: {
        Row: {
          id: number;
          reference: string;
          date: string;
          time_of_entry: string | null;
          border_point_id: number;
          officer_id: number;
          crop_product_id: number;
          crop_id: number;
          directorate_id: number | null;
          department_id: number | null;
          direction: string;
          quantity: number;
          unit: string;
          standard_quantity: number | null;
          standard_unit: string | null;
          country_origin: string | null;
          country_destination: string | null;
          vehicle_reg: string | null;
          consignment_doc: string | null;
          trader_company: string | null;
          transporter: string | null;
          permit_number: string | null;
          packaging_type: string | null;
          no_of_packages: number | null;
          purpose: string | null;
          variety: string | null;
          inspection_status: string | null;
          remarks: string | null;
          gps_coordinates: string | null;
          status: string;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: number;
          reference: string;
          date?: string;
          time_of_entry?: string | null;
          border_point_id: number;
          officer_id: number;
          crop_product_id: number;
          crop_id: number;
          directorate_id?: number | null;
          department_id?: number | null;
          direction: string;
          quantity: number;
          unit: string;
          standard_quantity?: number | null;
          standard_unit?: string | null;
          country_origin?: string | null;
          country_destination?: string | null;
          vehicle_reg?: string | null;
          consignment_doc?: string | null;
          trader_company?: string | null;
          transporter?: string | null;
          permit_number?: string | null;
          packaging_type?: string | null;
          no_of_packages?: number | null;
          purpose?: string | null;
          variety?: string | null;
          inspection_status?: string | null;
          remarks?: string | null;
          gps_coordinates?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: number;
          reference?: string;
          date?: string;
          time_of_entry?: string | null;
          border_point_id?: number;
          officer_id?: number;
          crop_product_id?: number;
          crop_id?: number;
          directorate_id?: number | null;
          department_id?: number | null;
          direction?: string;
          quantity?: number;
          unit?: string;
          standard_quantity?: number | null;
          standard_unit?: string | null;
          country_origin?: string | null;
          country_destination?: string | null;
          vehicle_reg?: string | null;
          consignment_doc?: string | null;
          trader_company?: string | null;
          transporter?: string | null;
          permit_number?: string | null;
          packaging_type?: string | null;
          no_of_packages?: number | null;
          purpose?: string | null;
          variety?: string | null;
          inspection_status?: string | null;
          remarks?: string | null;
          gps_coordinates?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string | null;
        };
      };
    };
  };
}
